name: Conda package

on:
  push:
    branches:
      - master
  pull_request:


env:
  PACKAGE_NAME: itt-python

jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set pkgs_dirs
        run: |
          echo "pkgs_dirs: [~/.conda/pkgs]" >> ~/.condarc

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install conda-build
        run: conda install conda-build

      - name: Build conda package
        run: |
          CHANNELS="-c conda-forge --override-channels"
          VERSIONS="--python ${{ matrix.python }}"
          conda build \
            $VERSIONS \
            $CHANNELS \
            conda-recipe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} Python ${{ matrix.python }}
          path: /usr/share/miniconda/conda-bld/linux-64/${{ env.PACKAGE_NAME }}-*.tar.bz2

  build_and_test_windows:
    runs-on: windows-latest

    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
    env:
      conda-bld: C:\Miniconda\conda-bld\win-64\

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          conda-build-version: "*"
          activate-environment: true
          python-version: ${{ matrix.python }}

      - name: Build conda package
        run: conda build --python ${{ matrix.python }} -c conda-forge --override-channels conda-recipe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }} Python ${{ matrix.python }}
          path: ${{ env.conda-bld }}${{ env.PACKAGE_NAME }}-*.tar.bz2

